name: deploy.yml
on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 516669727885.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REPOSITORY: test-app

jobs:
  push-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::516669727885:role/test-gha-push
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          
  deploy:
    needs: [push-ecr]
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::516669727885:role/test-gha-apply
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - run: terraform -chdir=infra init

      - run: terraform -chdir=infra apply -auto-approve -var="image_tag=${{ github.sha }}"

      - run: |
          echo "### Deployed" >> $GITHUB_STEP_SUMMARY
          terraform -chdir=infra output -raw app_url >> $GITHUB_STEP_SUMMARY
